baseurl:
url: https://iscas-glm.github.io
title: glm@iscas
subtitle: "Rust learner,in Rust we trust"
description: "glm@iscas's personal page"
date_format: "ordinal"
# timezone: Asia/
encoding: "utf-8"
side_bar_repo_limit: 5

author: Guo Limin
organization: ISCAS
organization_url: http://www.is.cas.cn/
github_username: iscas-glm
location: Xiamen, China
email: glm233@foxmail.com 
 
# Navigation
navs:
  -
    href: /
    label: Homepage
    
  -
    href: /article/
    label: Article
    
  -
    href: /life/
    label: Life


  # -
  #   href: /links/
  #   label: Links

# RSS
name:     glm@iscas's homepage
subscribe_rss: /feed.xml
baidu-analysis: e589b334f4625414ca59828e18e21956
# Jekyll
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    math_engine: katex
highlighter: rouge
paginate: 8
lsi: false
quiet: false
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate 
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    life:
        output: true
        permalink: /life/:path/

repository: iscas-glm/iscas-glm.github.io

# Search
simple_jekyll_search:
    fulltext: false # full text search enable
    limit: 10 # limitation of the search results to show

# Analytics
google:
    analytics_id: UA-80669434-1
github: [metadata]

#Comment


